### ISSUE TITLE
Can these actions be tested?

### ISSUE THREAD

**Issue by MaxGhenis** [joshlarsen/jekyll4-deploy-gh-pages#11]
Using other workflows, integrating testing isn't straightforward (https://github.com/jeffreytse/jekyll-deploy-action/issues/5 and https://github.com/jeffreytse/jekyll-deploy-action/issues/9). With this action is it possible to have an action that tests whether the site builds in a PR, and then a separate one that deploys upon merging?

**Comment by joshlarsen** [comment]
@MaxGhenis I don't maintain this Action anymore. There are better base images now that support a bunch of modern build tools, including a more recent Bundler so you don't need to build a custom Docker image. [Here](https://gist.github.com/joshlarsen/4e7851e91ef4a7db8dfa89c2f993bb23) is an example of how I use it now, with a custom `deploy.sh` that you can modify to create a PR instead of deploy. You could omit the JavaScript/Yarn setup if you're not using any Node packages.
